name: 'Git Metadata'
description: 'Extract metadata of your git repository'

outputs:
  tag-current:
    description: "Current tag name"
    value: ${{ steps.run.outputs.tag-current }}

  tag-last:
    description: "Last tag name"
    value: ${{ steps.run.outputs.tag-last }}

  changes-since-last:
    description: "Changes since last tag"
    value: ${{ steps.run.outputs.changes-since-last }}

  changes-formatted:
    description: "Markdown-Formatted version of changes-since-last"
    value: ${{ steps.run.outputs.changes-formatted }}

runs:
  using: "composite"
  steps:
    - id: run
      run: bash run.sh
      shell: bash
